version: "3.3"

services:

  service-status:
    image: albertogviana/docker-swarm-service-status:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
         delay: 5s
      resources:
         reservations:
           memory: 20M
         limits:
           memory: 50M
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - service-status

networks:
  service-status:
    external: true
